name: expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.3.3
  path: ^1.8.3
  google_generative_ai: ^0.4.0
  speech_to_text: ^7.0.0
  fl_chart: ^0.68.0
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.5
  csv: ^5.1.1
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-Bold.ttf
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true